config/routes.rb
Rails.application.routes.draw do
  root to:'static_pages#home'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments, only: [:create, :destroy]

  match '/signup',to:  'users#new', via: 'get'
  match '/signin',to:  'sessions#new', via: 'get'
  match '/signin',to:  'sessions#destroy', via: 'delete'

  get 'static_pages/home'
  get 'static_pages/about'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates_presence_of :user_id, :content
  validates :content, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates_presence_of :name, :email
  validates :name, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  has_secure_password

  before_save { self.email.downcase! }
  before_create :create_remember_token

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.digest(SecureRandom.urlsafe_base64.to_s)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      flash[:success] = "Comment posted!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @comment.destroy
    redirect_to root_url
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def correct_user
    @comment = current_user.comments.find(id: params[:id])
  rescue
    redirect_to root_url 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:sessions][:email].downcase)
    if user && user.authenticate(params[:sessions][:password])
      sign_in user
      redirect_back_or_to user
    else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end    

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @comment = current_user.comments.build if signed_in?
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    page = params[:page] || 1
    @user = User.find(params[:id])
    @comments = @user.comments.paginate(page: page)
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Games, Books and Anime!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    token = SecureRandom.urlsafe_base64
    cookies.permanent[:remember_token] = token
    digest = User.digest(token)
    user.update_attribute(:remember_token, digest)
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
              User.digest(SecureRandom.urlsafe_base64))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in?
    current_user.present?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token( User.digest(cookies[:remember_token]) )
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or_to(default = root_url)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:redirect_to] = request.url if request.get?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end 
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.  
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/comments/_comment.html.erb
<li>
  <span class="content"><%= comment.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
  </span>
  <% if current_user?(comment.user) %>
    <%= link_to "delete", comment, method: :delete,
                                    data: { confirm: "You sure?" },
                                    title: comment.content %>
  <% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <nav>
          <li><%= link_to "Games, books and anime", "/static_pages/home", id: "logo" %></li>
          <div class="nav-collapse collapse">
            <ul class="nav pull-right">
              <li><%= link_to "Home", "#" %></li>
              <li><%= link_to "About", "#" %></li>
              <% if signed_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Sign out", signin_path, method: 'delete' %></li>
                  </ul>
                </li>
              <% else %>
                <li><%=link_to "Sign in", signin_path %></li>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </div>
  </header>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value%></div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/shared/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Write comment ..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>*<%=msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.comments.count, "comment")%>
</span>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Games,books and anime') %>

<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/comment_form' %>        
      </section>
    </aside>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Games,books and anime</h1>

    <%= link_to "Sign up", signup_path, class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("logo.png", alt: "Logo"), '#' %>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%=gravatar_for @user, { size: 100 } %>
    <a href="https://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size:80 %>
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %>
        <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
      <%= gravatar_for @user, { size: 100 } %>
      <%= @user.name %>
      </h1>      
    </section>
  </aside>
</div>